### ISSUE TITLE
Shield of the Falling Stars is missing the +10% missile resistance on description.

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#21]
Title.

**Comment by morpheus562** [comment]
Are you looking at SHLD07.ITM or SHLD07A.ITM in game?

**Comment by jweinr** [comment]
SHLD07.ITM
The effect is correctly applied tho, at least according to character sheet.

**Comment by morpheus562** [comment]
What language are you playing in and what does your item description look like? Can you please post it? What other item mods are you using?

**Comment by jweinr** [comment]
English.

Screenshot from EEKeeper item browser:
![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/62143a6a-1b70-4be9-87b9-0a49a8523000)

Modlist:
BG1 NPC Project
BG1 NPC Project Music
BG1 Unfinished Business
Tweaks Anthology
Klatu's Tweaks and Fixes (only fix applied is enable haste while free action)
Portraits Everywhere
SCS
Thalan Item Upgrade Mod

Forgotten Armament was installed last (just today).

**Comment by morpheus562** [comment]
Figured it out and it will be fixed in the next release. The BGEE version provides +5 AC vs. Missile while the BG2EE version provides +4. I do a check on the text and update, so I updated the check slightly to remove the +4 it was checking for.

**Comment by jweinr** [comment]
Awesome, thanks for the update!




Figured it out and it will be fixed in the next release. The BGEE version

**Comment by morpheus562** [comment]
v3.0 corrects
