### ISSUE TITLE
Short Sword of Backstabbing applying + x2 multiplier

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#23]
Title.
On Alora with natural x4, upgrades her to x6.

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/899fbda0-18bf-48e5-b805-c226f11b4edf)
![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/11cec29d-21ba-45fd-a532-e888fc7da3f9)
![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/c22b352d-a0d3-4da1-8380-4f722f11190b)
![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/e52e88df-69e2-4e25-951c-667ff8ebaf90)

**Comment by morpheus562** [comment]
Thank you! I updated the file and it should be corrected in the next release.

**Comment by morpheus562** [comment]
v3.0 corrects
