### ISSUE TITLE
Beruel's Retort +1

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#24]
Typo on github item description, reads "Ber**eu**l's Retort +1" should be "Ber**ue**l's Retort +1"

Also, i think Taerom Fuiruim's stock should be updated, otherwise he's selling a bunch of copies of a now unique thrown weapon.

**Comment by morpheus562** [comment]
The component iterates through all stores and identifies ones that sell this item and reduces the quantity to 1 available. Do you have other mods installed that may alter quantities?

**Comment by basicals** [comment]
Indeed I have Tweaks Anthology with the "Stores Sell Higher Stacks of Items" component installed.
Forgotten armaments is installed after Tweaks tho.

_Stores Sell Higher Stacks of Items
All games except PsT, PsTEE

This component will alter all stores in the game to use higher stacks of arrows, bolts, bullets, darts, throwing axes, throwing daggers, and (where available) throwing hammers. This component will affect all stores in the game, including ones introduced by mods._

**Comment by morpheus562** [comment]
Unable to replicate this issue.
