### ISSUE TITLE
WARNING: no effects altered on AMUL27.ITM

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#27]
Hello!, found a warning while installing version 3.0 on a clean windows install of latest BG2EE Steam.
for whatever reason the install is skipping the amulet of seldarine AMUL27.ITM
Debug attached.

[Setup-forgotten-armament.txt](https://github.com/Gibberlings3/Forgotten-Armament/files/12386967/Setup-forgotten-armament.txt)

**Comment by morpheus562** [comment]
I'm guessing you have another mod that alters it prior to Forgotten Armament.

**Comment by basicals** [comment]
I checked for empty override folder and verified file integrity on steam
already.
Anything else I should do to ensure an even cleaner install? Lol

**Comment by morpheus562** [comment]
Got it figured out. It will be corrected in the next patch.

**Comment by basicals** [comment]
Awesome, thank you so much!

**Comment by basicals** [comment]
This is weird... just checked the amulet ingame and it's 25% magic resistance. I'm confused.

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/7d01cfef-9a71-44c4-8999-acd1388a2bf3)

**Comment by morpheus562** [comment]
It is updating the text, but the actual bonus has not been altered in your game. This is corrected in the next patch.

**Comment by basicals** [comment]
That was quick, is there a github phone app or smthing.

I'm curious, is the text stored somewhere else, like dialog.tlk?

Thanks !

**Comment by morpheus562** [comment]
I get an email whenever I get a message on git for my mods. Text is stored in dialog.tlk. if you have near infinity, it may be easier to simply update op 166 on the item to provide 25 instead of 10 magic resist.

**Comment by basicals** [comment]
Gonna do just that, gracias por explaining.
Will NI set a new item on override folder, so no editing of the game base files? Don't wanna go and mess with that.
Can't really test myself because my override folder is now out of bounds to windows, 15.258 elements insta-crash the file explorer if i try to navigate through it lmao.

**Comment by morpheus562** [comment]
Gonna close this as its slated for the next release
