### ISSUE TITLE
Short description of the mod is incorrect

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#28]
The short description of the mod is incorrect (in file forgotten-armament.ini):
Currently:
# Short description of the mod, main goals, features etc
Description = This mod is a collection of player AI scripts designed for use in Baldur's Gate II: Enhanced Edition and the Enhanced Edition Trilogy. With these scripts, you can focus on the fighting aspect of combat while these take care of the nuances in the background. Of note, these scripts allow easy pre-buffing of all characters with a keystroke, intelligent debuffing of enemy protections, and smart use of defensive spells and abilities.

**Comment by morpheus562** [comment]
corrected
