### ISSUE TITLE
No extra damage on Bone Club?

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#30]
I'm seeing no extra damage on mummies, skeleton warriors.
Could it be the text updated, but not the actual item damage?

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/fa22a473-cef3-40c1-9567-bf28d3b9fc0f)
![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/abc6e56b-44e8-45c4-a597-b3c4c6c93b3d)
![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/d860d3bf-9517-4e1f-b5d9-d680d7806145)

**Comment by morpheus562** [comment]
Typo in eff was corrected which caused the bug. I listed ~mobln232~ instead of ~mobl232~. This is fixed in next  release.
