### ISSUE TITLE
Axe of Dead Illusk usable by clerics

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#31]
It shouldn't, as indicated on item description.

**Comment by morpheus562** [comment]
Item flags are set appropriately, so it is likely another mod (like the one found in Tweaks Anthology) that opens up the restriction to allow clerics to use it.

**Comment by basicals** [comment]
OK, i went into it again on a clean install, indeed a single class cleric can't use it, but somehow my stalker dualed to cleric can. Which afaik shouldn't.


![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/97f78991-4c88-45c1-adc2-36b5844db1fa)

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/7f3bebb8-288a-49ee-9263-b6ddf7c69ed9)
