### ISSUE TITLE
Axe of Dead Illusk: Part 2

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#34]
Allright so I checked it on NearInfinity, and it's missing three restrictions which allows it to be used by dual or multi clerics, which shouldn't.

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/dd72c4cc-02cc-4719-bb63-9d6ded679c99)

**Comment by morpheus562** [comment]
Thank you, fixed for next release.
