### ISSUE TITLE
Version 4.0: Rakshasa Staff is still bugged

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Forgotten-Armament#36]
It now shows two weapon abilities when right-clicking, none of which do anything.

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/17f6ae0a-005b-47c3-862d-99e238f49268)

![image](https://github.com/Gibberlings3/Forgotten-Armament/assets/6373803/fab3ac52-584d-4ee0-aba2-419ea73e36bd)

Good part is I've now properly learned how to spell rakshashahah in my head.

**Comment by morpheus562** [comment]
fixed now
